import { Project, SkillItem, ContactInfo } from './types';
import heroAdrianImg from './assets/images/regenerated_image_1788883214513.jpg';
import aboutDeskImg from './assets/images/about_editor_desk_1788879826051.jpg';
import thumbBodybuildingDietImg from './assets/images/thumb_bodybuilding_diet.jpg';
import thumbEliteGeneticsImg from './assets/images/thumb_elite_genetics.jpg';
import thumbSteroidSideEffectsImg from './assets/images/thumb_steroid_side_effects.jpg';
import thumbSyntholDisastersImg from './assets/images/thumb_synthol_disasters.jpg';
import thumbRiggedOlympiaImg from './assets/images/thumb_rigged_olympia.jpg';
import thumbBodybuildingDeathsImg from './assets/images/thumb_bodybuilding_deaths.jpg';
import thumbTedBundyImg from './assets/images/thumb_ted_bundy.jpg';
import thumbEdGeinImg from './assets/images/thumb_ed_gein.jpg';
import thumbJeremyBamberDnaImg from './assets/images/thumb_jeremy_bamber_dna.jpg';
import thumbWhiteHouseFarmImg from './assets/images/thumb_white_house_farm.jpg';
import thumbJohnListImg from './assets/images/thumb_john_list.jpg';

export const ASSETS = {
  hero: heroAdrianImg,
  about: aboutDeskImg,
};

export const PROJECTS: Project[] = [
  {
    id: 'bodybuilding-diet-explained',
    title: 'Every Era of Bodybuilding Dieting Explained (What The Pros Actually Ate)',
    category: 'FITNESS DOCUMENTARY',
    description: 'A comprehensive deep dive into 60 years of bodybuilding nutrition—from Golden Era steak & eggs to modern mass monster protocols.',
    duration: '09:05',
    thumbnail: thumbBodybuildingDietImg,
    youtubeUrl: 'https://youtu.be/BbVjpE4XkvE?si=VK_nkgP8pi2DZJ1P',
    youtubeId: 'BbVjpE4XkvE',
    views: '2.1K+',
    retention: '78%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Documentary narrative structure across 7 historical eras',
      'Dynamic vintage photo motion & Ken Burns parallax',
      'Custom kinetic text highlighting macro breakdowns',
      'Film grain texture & period-accurate color transitions',
    ],
  },
  {
    id: 'elite-genetics-explained',
    title: 'Every Sign You Have Elite Genetics Explained',
    category: 'ANATOMY & PHYSIQUE',
    description: 'An anatomical breakdown of what separates elite bodybuilding genetics—clavicle width, muscle belly insertions, tendon ratios, and genetic ceilings.',
    duration: '10:21',
    thumbnail: thumbEliteGeneticsImg,
    youtubeUrl: 'https://youtu.be/r93E66KUHfY?si=dVNsepe7E_0NTDO-',
    youtubeId: 'r93E66KUHfY',
    views: '6.1K+',
    retention: '81%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Muscle insertion anatomical motion overlays',
      'Fast-paced comparison zooms & tier breakdowns',
      'Kinetic typography for scientific terminology',
      'Impact sound design & custom riser effects',
    ],
  },
  {
    id: 'steroid-side-effects-explained',
    title: 'Every Steroid Side Effect Explained (What Nobody Shows You)',
    category: 'FITNESS EXPOSÉ',
    description: 'The raw reality behind bodybuilding pharmacology—from left ventricular hypertrophy to hormonal crashes, organ strain, and mental side effects.',
    duration: '11:45',
    thumbnail: thumbSteroidSideEffectsImg,
    youtubeUrl: 'https://youtu.be/7nbab4rX15o?si=kB8fOKs_xxh_jX0c',
    youtubeId: '7nbab4rX15o',
    views: '8.5K+',
    retention: '79%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Atmospheric suspense color grading & dark palette',
      'Medical MRI scan & diagram motion graphics',
      'Tense audio distortion & caution risers',
      'Dynamic split-screen historical footage timeline',
    ],
  },
  {
    id: 'synthol-disasters-explained',
    title: 'Every Synthol Disaster Explained',
    category: 'BODYBUILDING ARCHIVES',
    description: 'Investigating 8 extreme cases of site enhancement oil disasters—infections, surgical drainage, near-amputations, and the pursuit of synthetic mass.',
    duration: '08:50',
    thumbnail: thumbSyntholDisastersImg,
    youtubeUrl: 'https://youtu.be/MaCrg9Vl1OU?si=B6O_PJOh9H4lgiGp',
    youtubeId: 'MaCrg9Vl1OU',
    views: '12K+',
    retention: '84%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Fast-paced investigative documentary rhythm',
      'Archival television broadcast & 2.5D photo restoration',
      'Surgical case timeline motion graphics',
      'Subtle glitch overlays & dramatic impact hits',
    ],
  },
  {
    id: 'rigged-olympia-explained',
    title: 'Every Rigged Mr. Olympia Explained',
    category: 'SPORTS CONTROVERSY',
    description: 'Deconstructing 6 controversial Mr. Olympia decisions—from 1980 Sydney to 2007, dissecting scorecard politics, judge ties, and athlete protests.',
    duration: '14:18',
    thumbnail: thumbRiggedOlympiaImg,
    youtubeUrl: 'https://youtu.be/FfdA0XkVXzg?si=w-v5OoBn0l0ZEPn0',
    youtubeId: 'FfdA0XkVXzg',
    views: '15K+',
    retention: '82%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Vintage broadcast & VHS emulation effects',
      'Side-by-side physique freeze-frame analysis',
      'Scorecard graphic dynamic rebuilds',
      'Investigative narrative pacing with Foley sound design',
    ],
  },
  {
    id: 'bodybuilding-deaths-explained',
    title: 'Every Bodybuilding Death Explained in 12 Minutes',
    category: 'INVESTIGATIVE DOC',
    description: 'A respectful, hard-hitting analysis examining the tragic casualties of modern competitive bodybuilding—diuretic abuse, cardiac arrest, and extreme contest prep.',
    duration: '12:00',
    thumbnail: thumbBodybuildingDeathsImg,
    youtubeUrl: 'https://youtu.be/nXGyog-HFys?si=I82CS1D4mOUd7Nso',
    youtubeId: 'nXGyog-HFys',
    views: '18K+',
    retention: '86%',
    client: 'Professor Mass',
    channel: 'Professor Mass',
    style: 'Storyboard',
    techniques: [
      'Respectful dark cinematic color grading',
      'Chronological memorial timeline motion graphics',
      'Atmospheric low-drone Foley sound design',
      'High-retention documentary cutting rhythm',
    ],
  },
  {
    id: 'ted-bundy-monster',
    title: 'Ted Bundy: The Real Monster Behind The Perfect Image',
    category: 'TRUE CRIME DOC',
    description: 'An investigative documentary deconstructing the charismatic serial killer myth, uncovering the methods, investigative failures, and hidden psychology.',
    duration: '18:42',
    thumbnail: thumbTedBundyImg,
    youtubeUrl: 'https://youtu.be/cTSUIjSfLiw?si=3LiPzvEYWGIX3g0T',
    youtubeId: 'cTSUIjSfLiw',
    views: '24K+',
    retention: '85%',
    client: 'Lost Eras',
    channel: 'Lost Eras',
    style: 'Documentaries',
    techniques: [
      '2.5D archival photograph parallax reconstruction',
      'Atmospheric low-drone sound design with progressive tension build-ups',
      'Kinetic animation of vintage newspaper clippings and trial records',
      'Desaturated noir color grading with dramatic high-contrast curves',
    ],
  },
  {
    id: 'ed-gein-psycho',
    title: "THE REAL STORY Behind Psycho: Ed Gein's Skin Suits, 10 Human Heads & Grave Robberies Revealed",
    category: 'HISTORICAL CRIME DOC',
    description: 'The disturbing true story that inspired horror film classics: the psyche of Ed Gein, the isolated Plainfield homestead, and macabre discoveries.',
    duration: '22:15',
    thumbnail: thumbEdGeinImg,
    youtubeUrl: 'https://youtu.be/D2pOJW4WFoU?si=PKYN6QdhW7LhbIQ_',
    youtubeId: 'D2pOJW4WFoU',
    views: '31K+',
    retention: '87%',
    client: 'Lost Eras',
    channel: 'Lost Eras',
    style: 'Documentaries',
    techniques: [
      'Authentic analog film textures (16mm grain & dust overlays)',
      '3D spatial floor plan reconstruction with vintage maps',
      'Immersive micro-Foley sound design (creaking doors, footsteps, cold winds)',
      'Chronological investigative pacing with cinematic editorial rhythm',
    ],
  },
  {
    id: 'jeremy-bamber-dna',
    title: 'JEREMY BAMBER: GUILTY OR INNOCENT? | The DNA Evidence That Changes EVERYTHING',
    category: 'FORENSIC INVESTIGATION',
    description: 'An in-depth forensic examination of new biological evidence, ballistic contradictions, and the legal battle challenging a decades-old conviction.',
    duration: '16:30',
    thumbnail: thumbJeremyBamberDnaImg,
    youtubeUrl: 'https://youtu.be/s7c4S3YekxA?si=1p0NDXtBw9Vb1Y9c',
    youtubeId: 's7c4S3YekxA',
    views: '19K+',
    retention: '83%',
    client: 'Lost Eras',
    channel: 'Lost Eras',
    style: 'Documentaries',
    techniques: [
      'Explainer motion graphics detailing DNA profiles and forensic reports',
      'Dynamic shooting timeline visualization with ballistic reconstruction',
      'Rhythmic editorial cut alternating prosecution and defense theses',
      'Forensic audio restoration emphasizing emergency police call recordings',
    ],
  },
  {
    id: 'white-house-farm-doc',
    title: "The Real White House Farm Story (What They Didn't Tell You About JEREMY BAMBER) FULL DOCUMENTARY",
    category: 'FEATURE DOCUMENTARY',
    description: 'Feature-length documentary investigating the White House Farm tragedy in Essex: untold background, inheritance motives, and fatal night reconstruction.',
    duration: '28:40',
    thumbnail: thumbWhiteHouseFarmImg,
    youtubeUrl: 'https://youtu.be/gOJQPXdDzuo?si=QIA4abwtUXg-hsDk',
    youtubeId: 'gOJQPXdDzuo',
    views: '45K+',
    retention: '88%',
    client: 'Lost Eras',
    channel: 'Lost Eras',
    style: 'Documentaries',
    techniques: [
      'Classic 4-act long-form documentary narrative structure',
      'Cold-tone cinematic color grading with dramatic contrast',
      'Original scoring arrangement built with tense acoustic suspense textures',
      'Animated genealogical charts and investigative map route motion',
    ],
  },
  {
    id: 'john-list-breeze-knoll',
    title: "The Real John List Story (What They Didn't Tell You About Breeze Knoll) Full Documentary",
    category: 'COLD CASE DOCUMENTARY',
    description: 'The harrowing Breeze Knoll tragedy and the astonishing 18-year manhunt resolved through a televised forensic age-progression bust.',
    duration: '24:10',
    thumbnail: thumbJohnListImg,
    youtubeUrl: 'https://youtu.be/Owjb_EwYEc0?si=WE4S4V7ecSYDDtX5',
    youtubeId: 'Owjb_EwYEc0',
    views: '38K+',
    retention: '86%',
    client: 'Lost Eras',
    channel: 'Lost Eras',
    style: 'Documentaries',
    techniques: [
      'Seamless transitions between 1970s archives and 1989 television broadcasts',
      'Match-cut composition aligning the forensic sculpture with the real arrest',
      'Micro-Foley textures featuring analog ticking clocks and vintage magnetic tape',
      'Psychological suspense pacing engineered for peak audience retention',
    ],
  },
];

export const SKILLS: SkillItem[] = [
  {
    name: 'Premiere Pro',
    role: 'Editing & Post',
    badge: 'Pr',
    color: '#9999FF',
    bgColor: '#161426',
    borderColor: '#302652',
  },
  {
    name: 'After Effects',
    role: 'Motion Graphics',
    badge: 'Ae',
    color: '#D291FF',
    bgColor: '#21152d',
    borderColor: '#43265d',
  },
  {
    name: 'Photoshop',
    role: 'Thumbnails & Design',
    badge: 'Ps',
    color: '#31A8FF',
    bgColor: '#101d2d',
    borderColor: '#193f66',
  },
];

export const CONTACT: ContactInfo = {
  email: 'adriansilva1016d@gmail.com',
  discord: 'adrianvinicius8488',
  twitter: '@adriansilva1012',
  location: 'Los Angeles, USA',
};
